export const coffeeArr = [
    {id: 1, name: 'Esspreso kratki', text: 'Svojom bogatom aromom i punim ukusom, ova mala ali moćna kafica  čini savršen početak dana.'},
    {id: 2, name: 'Esspreso kratki sa mlekom', text: 'Intenzivna kafa obogaćena kremastim dodatkom mleka, stvarajući  zadovoljavajući i bogat ukus koji osvaja.'},
    {id: 3, name: 'Esspreso dugi', text: 'Produžena verzija espressa, sa malo više vode, rezultira blažom notom  i produženim uživanjem u kafi.'},
    {id: 4, name: 'Esspreso dugi sa mlekom', text: 'Espresso obogaćen mlekom za savršenu harmoniju arome i ukusa.  Idealan izbor za one koji vole blaži ukus.'},
    {id: 5, name: 'Americano', text: 'Osvežavajući spoj espresso kafe i vruće vode, idealan za laganije uživanje,  za bilo koje doba dana.'},
    {id: 6, name: 'Americano sa mlekom', text: 'Kombinacija laganog osvežavajućeg ukusa americana sa kremastim  mlekom, za izvanredno uravnotežen napitak.'},
    {id: 7, name: 'Macchiato', text: 'Ova balansirana kombinacija nudi savršeno iskustvo za one koji vole  punoću espressa uz blagi dodir mleka.'},
    {id: 8, name: 'Espresso Macchiato', text: 'Jednostavan, ali izrazito ukusan napitak, koji kombinuje čist, jak ukus  espressa sa malo mleka.'},
    {id: 9, name: 'Cappuccino', text: 'Klasični italijanski napitak koji spaja intenzivnu aromu espressa sa kremastim mlekomi penom na vrhu.'},
    {id: 10, name: 'Latte', text: 'Lagani napitak koji kombinuje intenzivan ukus espressa sa nežnom i  kremastom teksturom mleka.'},
    {id: 11, name: 'Mocha  Bela Čokolada', text: 'Osvežavajuća poslastica koja spaja bogati ukus bele čokolade sa  intenzivnom aromom espressa i mlečne pene.'},
    {id: 12, name: 'Mocha Crna Čokolada', text: 'Zavodljivi napitak koji kombinuje intenzivan ukus tamne čokolade sa  espressom i kremastom mlečnom penom.'},
    {id: 13, name: 'Mocha Lešnik', text: 'Napitak koji spaja intenzivan ukus lešnika sa aromatičnim espressom i  kremastom mlečnom penom.'},
    {id: 14, name: 'Flat White', text: 'Elegantan napitak koji kombinuje intenzivnu aromu espressa i mleka sa  tankim slojem pene na vrhu.'},
    {id: 15, name: 'Lungo Ristretto', text: 'Produžena verzija klasičnog espressa, ali sa malo intenzivnijim ukusom i  savršenom ravnotežom.'},
    {id: 16, name: 'Affogato', text: 'Jednostavna, izuzetno ukusna poslastica koja spaja intenzivan ukus  espressa sa osvežavajućim sladoledom.'},
    {id: 17, name: 'Affogato sa sladoledom', text: 'Slatka i osvežavajuća poslastica koja spaja intenzivan ukus espressa sa kremastom slatkoćom sladoleda.'},
    {id: 18, name: 'Frappuccino', text: 'Osvežavajući napitak koji spaja intenzivan ukus espressa sa kremastom  slatkoćom mleka i sladoleda.'},
    {id: 19, name: 'Turkish Coffee', text: 'Tradicionalni napitak koji se priprema na poseban način, pružajući  intenzivan ukus i bogatu aromu.'},
    {id: 20, name: 'Turkish Coffee sa mlekom', text: 'Turska tradicionalna kafa sa mlekom kombinuje jaku aromu turske kafe  sa kremastim mlekom.'},
    {id: 21, name: 'Cold Brew', text: 'Osvežavajući napitak koji se priprema na poseban način, pružajući glatku  i osvežavajuću kafu bez gorčine.'},
    {id: 22, name: 'Cold Brew sa mlekom', text: 'Cold Brew sa mlekom je osvežavajući napitak koji spaja glatku i  osvežavajuću kafu sa kremstim mlekom.'},
    {id: 23, name: 'Ice Coffee', text: 'Osvežavajući napitak koji spaja intenzivan ukus kafe sa dodatkom leda za  uživanje u svakom gutljaju.'},
    {id: 24, name: 'Ice Coffee sa sladoledom', text: 'Osvežavajući napitak koji spaja intenzivan ukus kafe sa kremastom  slatkoćom sladoleda i dodatkom leda.'},
    {id: 25, name: 'Ice Coffee sa mlekom', text: 'Osvežavajući napitak koji spaja intenzivan ukus kafe sa kremastim  mlekom, idealan izbor za tople dane.'},
    {id: 26, name: 'Topla čokolada', text: 'Neodoljiva poslastica koja predstavlja spoj belgijske čokolade i mleka,  savršena za hladne dane.'},
]